require 'rubygems'
require 'capybara'
require 'capybara/dsl'
require 'connection_pool'
require File.dirname(__FILE__) + '/testconfig'
require_relative 'testconfig'
require 'capybara/cucumber'
require 'process'
require 'oci8'
require 'active_support/all'
require 'selenium-webdriver'
